name: CI/CD - Test & Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

permissions: write-all

jobs:
  test:
    name: Run Unit & E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests (Vitest)
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests (Playwright)
        run: npm run test:e2e

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project (Vite)
        run: npm run build

      - name: List Build Files
        run: ls -R dist

      - name: Upload Build Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
